export const apis = {
    login: '/login',
    allArticles: '/getAllArticles',
    updateSiteConfigurations: '/updateSiteConfigurations',
    getMeta: '/getMeta',
    getUser: '/getUser',
    createTempAdminUser: '/createTempAdminUser',
    getAllUsers: '/getAllUsers',
    saveMediaData: '/saveMediaData',
    updateMediaData: '/updateMediaData',
    getAllMedia: '/getAllMedia',
    createArticle: '/createArticle',
    updateArticle: '/updateArticle',
    addArticleCategory: '/addArticleCategory',
    updateUser: '/updateUser',
    getAllAdvertisers: '/getAllAdvertisers',
    createAdvertiser: '/createAdvertiser',
    updateAdvertiser: '/updateAdvertiser',
    addSubscriber: '/addSubscriber',
    getSubscribers: '/getSubscribers',
    removeCategory: '/removeCategory',
    addReaction: '/addReaction',
    removeReaction: '/removeReaction',
    getAllReactionsByArticleId: '/getAllReactionsByArticleId',
    getAllSponsors: '/getAllSponsors',
    createSponsor: '/createSponsor',
}